#!/usr/bin/env python
# coding: utf-8

# # Number Guessing Game

# In[30]:


import random
i=9
n=random.randint(0,100) #generate random number by computer

while (i>0):
 print("number of guesses left",i) #count and print number of guesses
 i = i - 1
 if i>-1:
    a = int(input("Enter number\n"))
    if 0 < a < 100: #check the input by user is valid or not
        
        if a==n: #check and compares input by user and random number generated by computer
            print("You have entered correct number")
            break
        elif a<n:
            print("Please Increase the value")
            continue
        else:
            print("please decrease the value")
            continue
    else:
        print("Please Enter Number Between 0 to 100 ")
        break
else:
    print("GAME OVER")
    print("The correct number is " + str(n))


# In[ ]:




